### ISSUE TITLE
Lighthouse complains about link target size

### ISSUE THREAD

**Issue by anguspiv** [anguspiv/www.angusp.com#51]
THe link tap target sizes are too small on mobile﻿

**Comment by ritikraina108** [comment]
Tap Target | Size | Overlapping Target
-- | -- | --
<a href="https://www.oneplus.in/8">ONEPLUS</a> | 66x18 | <a href="https://www.theindianhustlers.in/2020/05/best-whey-protein-brands-2020-in.html">guaranted B
